brew 'coreutils'
brew 'git'
brew 'node'
brew 'ansible'
brew 'wget'
brew 'Python'
brew 'cliclick'
brew 'java'
brew 'htop'
brew 'ffmpeg'
brew 'openjdk' 
brew 'ncdu' 

cask 'firefox'
cask 'google-chrome'
# cask 'microsoft-edge'
# cask 'microsoft-outlook'
cask 'visual-studio-code'
cask 'iterm2'
cask 'android-studio'
